---
- name: Reload postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded

# Требуется только при изменении port в postgresql.conf.
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
